version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: mtg-redis
    ports:
      - 6379:6379
    build:
      dockerfile: Redis.Dockerfile
      context: ./
    networks: 
      - mtg
    volumes:
      - ./mtg_collection/logs:/app/logs
  flask:
    build:
      context: ./
      dockerfile: Flask.Dockerfile
    container_name: mtg-flask
    volumes:
      - ./mtg_collection/api:/app
    ports: 
      - 5000:5000
    depends_on: 
      - redis
    networks:
      - mtg

networks:
  mtg: 
    driver: bridge
