version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: mtg-redis
    build:
      dockerfile: Redis.Dockerfile
      context: ./
    ports:
      - 6379:6379
    networks:
      - mtg
    volumes:
      - ./mtg_collection/logs:/app/logs

  flask:
    container_name: mtg-flask
    build:
      context: ./
      dockerfile: Flask.Dockerfile
    ports:
      - 5000:5000
    networks:
      - mtg
    volumes:
      - ./mtg_collection/api:/app/api
    env_file:
      - dev.env
    depends_on:
      - redis

networks:
  mtg:
    driver: bridge
