version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: mtg-redis
    build:
      context: ./
      dockerfile: Redis.Dockerfile
    ports:
      - 6379:6379
    networks:
      - mtg
    volumes:
      - ./mtg_collection/config:/app/config
      - ./mtg_collection/database:/app/database
      - ./mtg_collection/data:/data

  flask:
    container_name: mtg-flask
    build:
      context: ./
      dockerfile: Flask.Dockerfile
    ports:
      - 5000:5000
    networks:
      - mtg
    volumes:
      - ./mtg_collection/api:/app/api
    env_file:
      - dev.env
    depends_on:
      - redis

  frontend:
    container_name: mtg-frontend
    build:
      context: ./
      dockerfile: Frontend.Dockerfile
    ports: 
      - 8080:8080
    networks:
      - mtg
    volumes:
      - ./frontend/src:/app/src

networks:
  mtg:
    driver: bridge
